const columnList = [
  {
    dataIndex: 'id',
    width: 80,
    title: 'ID',
    noTable: false,
    sortable: 'custom',
  },
  {
    dataIndex: 'pic',
    width: 120,
    title: 'Cover',
    isForm: false,
    noTable: false,
    valueType: 'input',
    inputType: 'file',
    scopedSlots: { customRender: 'cover' },
  },
  {
    dataIndex: 'name',
    minWidth: 200,
    align: 'left',
    title: 'Name',
    isForm: true,
    valueType: 'input',
    prop: [{ required: true, message: 'กรุณาป้อนชื่อ' }],
    placeholder: 'กรุณาป้อนชื่อ',
  },
  {
    dataIndex: 'email',
    width: 300,
    minWidth: 300,
    align: 'left',
    title: 'Email',
    isForm: true,
    valueType: 'input',
    prop: [{ required: true, message: 'กรุณาป้อนอีเมล' }],
    placeholder: 'กรุณาป้อนอีเมล',
  },
  {
    dataIndex: 'password',
    width: 200,
    title: 'Password',
    isForm: true,
    noTable: true,
    valueType: 'input',
    inpuType: 'password',
    placeholder: 'กรุณาป้อนรหัสผ่าน',
    prop: [{ required: true, message: 'กรุณาป้อนรหัสผ่าน' }],
  },
  {
    dataIndex: 'phone',
    width: 200,
    title: 'Phone',
    isForm: true,
    valueType: 'input',
    placeholder: 'กรุณาป้อนเบอร์โทรศัพท์',
    prop: [{ required: true, message: 'กรุณาป้อนเบอร์โทรศัพท์' }],
  },
  {
    dataIndex: 'car_registation',
    width: 200,
    title: 'Car Code',
    isForm: true,
    valueType: 'input',
    placeholder: 'กรุณาป้อนรหัสรถ',
    prop: [{ required: true, message: 'กรุณาป้อนรหัสรถ' }],
  },
  {
    dataIndex: 'status',
    width: 200,
    title: 'Status',
    scopedSlots: { customRender: 'status' },
    isForm: true,
    valueType: 'switch',
  },
  {
    dataIndex: 'last_update',
    width: 200,
    title: 'Update At',
    scopedSlots: { customRender: 'date' },
    valueType: 'date-picker',
    attrs: {
      type: 'date',
      format: 'YYYY-MM-DD HH-mm-ss',
      'start-placeholder': 'Please select Date',
    },
  },
  {
    dataIndex: 'actions',
    fixed: 'right',
    width: 180,
    title: 'Actions',
    scopedSlots: { customRender: 'actions' },
  },
]

export { columnList }
