const columnList = [
  {
    dataIndex: 'id',
    width: 80,
    title: 'ID',
    noTable: false,
    sortable: 'custom',
  },
  {
    dataIndex: 'pic',
    width: 120,
    title: 'Cover',
    scopedSlots: { customRender: 'cover' },
  },
  {
    dataIndex: 'car_registation',
    width: 200,
    title: 'Car Code',
    isForm: true,
    valueType: 'input',
    prop: [{ required: true, message: 'กรุณาป้อนเลขทะเบียนรถ' }],
    placeholder: 'เลขทะเบียนรถ',
  },
  {
    dataIndex: 'gps_id',
    minWidth: 200,
    title: 'GPS ID',
    isForm: true,
    valueType: 'input',
    prop: [{ required: true, message: 'กรุณาป้อนรหัส GPS' }],
    placeholder: 'กรุณาป้อนรหัส GPS',
  },
  {
    dataIndex: 'car_detail',
    title: 'Car Detail',
    valueType: 'input',
    inpuType: 'textarea',
    noTable: true,
    isForm: true,
    placeholder: 'รายละเอียดรถ',
  },
  {
    dataIndex: 'status',
    width: 100,
    title: 'Status',
    scopedSlots: { customRender: 'status' },
    isForm: true,
    valueType: 'switch',
  },
  {
    dataIndex: 'last_update',
    width: 200,
    title: 'Update At',
    scopedSlots: { customRender: 'date' },
    valueType: 'date-picker',
    attrs: {
      type: 'date',
      format: 'YYYY-MM-DD HH-mm-ss',
      'start-placeholder': 'Please select Date',
    },
  },
  {
    dataIndex: 'actions',
    fixed: 'right',
    width: 180,
    title: 'Actions',
    scopedSlots: { customRender: 'actions' },
  },
]

export { columnList }
